### PR TITLE
[EAGLE-4200] - Remove runner stuffs

### PR DESCRIPTION
**Pull request by phatvo9**
### What

Remove runners from the current public SDK

### CODE REVIEW

**Comment by zeiler** [comment]
looks like there are some conflicts for some reason so I guess that's why tests didn't run?

**Comment by phatvo9** [comment]
> looks like there are some conflicts for some reason so I guess that's why tests didn't run?

I've resolved it, but still in processing updates. Not sure why.
image

**Comment by zeiler** [comment]
image
weird I'm seeing that.

**Comment by phatvo9** [comment]
> image weird I'm seeing that.

It's on the right side of PR title. Anyway, I pushed a dummy commit and it went through

**Review by ackizilkale — APPROVED** [review]
lgtm

**Review by zeiler — APPROVED** [review]

**Pull request merged**
