### PR TITLE
[BUG]: Aligned setup.py requirements with requirements.txt

### PR DESCRIPTION
**Pull request by tazarov**
Hi from the https://github.com/chroma-core/chroma team. 

There is a minor alignment between setup.py and requirements.txt, as this seems to be causing an issue with `clarifai` and `chromadb` packages co-existence.

### CODE REVIEW

**Comment by isaac-chung** [comment]
Hi @tazarov , thank you for raising this! 

CC @sainivedh

**Comment by tazarov** [comment]
@isaac-chung, the reason tests fail is you probably need to change your `pull_request:` to `pull_request_target:` in https://github.com/Clarifai/clarifai-python/blob/26d3198442f3cfdcdee3bc4e55a44cc7a0150fa1/.github/workflows/run_tests.yml#L9C5-L9C5

**Note**: This is generally a **security risk**, but if you're reviewing PRs before approving action runs, you should be fine.

**Review by sainivedh — APPROVED** [review]
Look good.
Thank you @tazarov

**Comment by isaac-chung** [comment]
@tazarov thanks for the tip! We've just merged that to the master branch. Would you mind merging that to this branch please? Thanks 🙏

**Pull request merged**
